/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-12-18 10:29:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import core.Watch;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1697639205471L));
    _jspx_dependants.put("jar:file:/C:/Users/szers/OneDrive/Máy%20tính/MyProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/MyProject/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("core.Watch");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Shopping Cart</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".shopping-cart {\r\n");
      out.write("	padding-bottom: 50px;\r\n");
      out.write("	font-family: 'Montserrat', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart.dark {\r\n");
      out.write("	background-color: #f6f6f6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .content {\r\n");
      out.write("	box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.075);\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .block-heading {\r\n");
      out.write("	padding-top: 50px;\r\n");
      out.write("	margin-bottom: 40px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .block-heading p {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	max-width: 420px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .dark .block-heading p {\r\n");
      out.write("	opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .block-heading h1, .shopping-cart .block-heading h2,\r\n");
      out.write("	.shopping-cart .block-heading h3 {\r\n");
      out.write("	margin-bottom: 1.2rem;\r\n");
      out.write("	color: #3b99e0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .items {\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .items .product {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("	padding-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .items .product .info {\r\n");
      out.write("	padding-top: 0px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .items .product .info .product-name {\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .items .product .info .product-name .product-info {\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .items .product .info .product-name .product-info .value\r\n");
      out.write("	{\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .items .product .info .quantity .quantity-input {\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	width: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .items .product .info .price {\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .summary {\r\n");
      out.write("	border-top: 2px solid #5ea4f3;\r\n");
      out.write("	background-color: #f7fbff;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .summary h3 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 1.3em;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("	padding-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .summary .summary-item:not(:last-of-type) {\r\n");
      out.write("	padding-bottom: 10px;\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("	border-bottom: 1px solid rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .summary .text {\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .summary .price {\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shopping-cart .summary button {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("	.shopping-cart .items .product .info {\r\n");
      out.write("		padding-top: 25px;\r\n");
      out.write("		text-align: left;\r\n");
      out.write("	}\r\n");
      out.write("	.shopping-cart .items .product .info .price {\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		font-size: 22px;\r\n");
      out.write("		top: 17px;\r\n");
      out.write("	}\r\n");
      out.write("	.shopping-cart .items .product .info .quantity {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.shopping-cart .items .product .info .quantity .quantity-input {\r\n");
      out.write("		padding: 4px 10px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	background: #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-w-40 {\r\n");
      out.write("	width: 40px !important;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("	box-shadow: 0 1px 15px 1px rgba(52, 40, 104, .08);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-product-color {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	margin: .144em;\r\n");
      out.write("	width: .875rem;\r\n");
      out.write("	height: .875rem;\r\n");
      out.write("	border-radius: 10rem;\r\n");
      out.write("	-webkit-box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.15) inset;\r\n");
      out.write("	box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.15) inset;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container px-3 my-5 clearfix\">\r\n");
      out.write("		<!-- Shopping cart table -->\r\n");
      out.write("		<div class=\"card\">\r\n");
      out.write("			<div class=\"card-header\">\r\n");
      out.write("				<h2>Shopping Cart</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card-body\">\r\n");
      out.write("				<div class=\"table-responsive\">\r\n");
      out.write("					<table class=\"table table-bordered m-0\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<!-- Add a new column for the checkbox -->\r\n");
      out.write("								<th class=\"text-center py-3 px-4\" style=\"width: 40px;\"><input\r\n");
      out.write("									type=\"checkbox\" id=\"selectAll\" onclick=\"selectAllItems()\">\r\n");
      out.write("								</th>\r\n");
      out.write("								<th class=\"text-center py-3 px-4\" style=\"min-width: 400px;\">Product\r\n");
      out.write("									Name &amp; Details</th>\r\n");
      out.write("								<th class=\"text-right py-3 px-4\" style=\"width: 100px;\">Price</th>\r\n");
      out.write("								<th class=\"text-center py-3 px-4\" style=\"width: 120px;\">Quantity</th>\r\n");
      out.write("								<th class=\"text-right py-3 px-4\" style=\"width: 100px;\">Total</th>\r\n");
      out.write("								<th class=\"text-center align-middle py-3 px-0\"><a href=\"#\"\r\n");
      out.write("									class=\"shop-tooltip float-none text-light\" title=\"\"\r\n");
      out.write("									data-original-title=\"Clear cart\"> <i\r\n");
      out.write("										class=\"ino ion-md-trash\"></i>\r\n");
      out.write("								</a></th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						");
 ArrayList<Watch> watchList = (ArrayList<Watch>) session.getAttribute("watchList"); 
      out.write("\r\n");
      out.write("							");
 Double gettotalAll = (Double) session.getAttribute("getTotalAll");
        double totalAll = (gettotalAll != null) ? gettotalAll : 0;
    
      out.write("\r\n");
      out.write("						\r\n");
      out.write("					<tbody>\r\n");
      out.write("    <!-- Sử dụng forEach để lặp qua danh sách sản phẩm từ Servlet -->\r\n");
      out.write("    ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /cart.jsp(214,4) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/cart.jsp(214,4) '${watchList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${watchList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /cart.jsp(214,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("item");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("        <tr>\r\n");
              out.write("            <!-- Add a checkbox for each item -->\r\n");
              out.write("            <td class=\"text-center py-3 px-4\">\r\n");
              out.write("                <input type=\"checkbox\" name=\"selectedItems\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.watchId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\r\n");
              out.write("            </td>\r\n");
              out.write("            <td class=\"p-4\">\r\n");
              out.write("                <div class=\"media align-items-center\">\r\n");
              out.write("                    <img src=\"data:image/jpg;base64,");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.base64Image}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" class=\"d-block ui-w-40 ui-bordered mr-4\" alt=\"\">\r\n");
              out.write("                    \r\n");
              out.write("                    <div class=\"media-body\">\r\n");
              out.write("                        <a href=\"#\" class=\"d-block text-dark\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.watchName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</a>\r\n");
              out.write("                        <small>\r\n");
              out.write("                            <span class=\"text-muted\">Color:</span>\r\n");
              out.write("                            <span class=\"ui-product-color ui-product-color-sm align-text-bottom\" style=\"background:;\"></span>\r\n");
              out.write("                            &nbsp;\r\n");
              out.write("                            <span class=\"text-muted\">Size: </span>\r\n");
              out.write("                            &nbsp;\r\n");
              out.write("                            <span class=\"text-muted\">Ships from: </span>\r\n");
              out.write("                        </small>\r\n");
              out.write("                    </div>\r\n");
              out.write("                </div>\r\n");
              out.write("            </td>\r\n");
              out.write("            <td class=\"text-right font-weight-semibold align-middle p-4\">\r\n");
              out.write("                <span id=\"price_");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.watchId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write('"');
              out.write('>');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.watchPrice}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</span>\r\n");
              out.write("            </td>\r\n");
              out.write("            <td class=\"align-middle p-4\">\r\n");
              out.write("    <input type=\"number\" class=\"form-control text-center\"\r\n");
              out.write("           value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.getQuantity()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\"\r\n");
              out.write("           onchange=\"updateQuantityInSession(");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.watchId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(", this.value)\">\r\n");
              out.write("</td>\r\n");
              out.write("            <td class=\"text-right font-weight-semibold align-middle p-4\">\r\n");
              out.write("                <span id=\"totalValue_");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.watchId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write('"');
              out.write('>');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.getTotal()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</span>\r\n");
              out.write("            </td>\r\n");
              out.write("            <td class=\"text-center align-middle px-0\">\r\n");
              out.write("                <a href=\"CartServlet?action=remove&id=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.watchId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("&total=");
              out.print( totalAll );
              out.write("\"\r\n");
              out.write("                    class=\"shop-tooltip close float-none text-danger\" title=\"\" data-original-title=\"Remove\">×</a>\r\n");
              out.write("            </td>\r\n");
              out.write("        </tr>\r\n");
              out.write("    ");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- / Shopping cart table -->\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"d-flex flex-wrap justify-content-between align-items-center pb-4\">\r\n");
      out.write("					<div class=\"mt-4\">\r\n");
      out.write("						<label class=\"text-muted font-weight-normal\">Promocode</label> <input\r\n");
      out.write("							type=\"text\" placeholder=\"ABC\" class=\"form-control\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex\">\r\n");
      out.write("						<div class=\"text-right mt-4 mr-5\">\r\n");
      out.write("							<label class=\"text-muted font-weight-normal m-0\">Discount</label>\r\n");
      out.write("							<div class=\"text-large\">\r\n");
      out.write("								<strong>$20</strong>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"text-right mt-4\">\r\n");
      out.write("							<label class=\"text-muted font-weight-normal m-0\">Total\r\n");
      out.write("								price</label>\r\n");
      out.write("							<div class=\"text-large\" id=\"totalPrice\">\r\n");
      out.write("								<strong>");
      out.print( totalAll );
      out.write("$</strong>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"float-right\">\r\n");
      out.write("						<a\r\n");
      out.write("						href=\"index.jsp\" class=\"btn btn-primary shadow-0\"> <i\r\n");
      out.write("						class=\"me-1 fa fa-shopping-basket\"></i> Back to\r\n");
      out.write("						shopping\r\n");
      out.write("					</a>\r\n");
      out.write("					");
 String username = (String) session.getAttribute("username"); 
      out.write(" \r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username != null ? 'checkout.jsp' : 'login.jsp'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-warning shadow-0\"> Buy now </a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function updateQuantityInSession(watchId, newQuantity) {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        url: 'CartServlet',\r\n");
      out.write("        data: {\r\n");
      out.write("            action: 'updateQuantity',\r\n");
      out.write("            id: watchId,\r\n");
      out.write("            quantity: newQuantity\r\n");
      out.write("        },\r\n");
      out.write("        success: function(response) {\r\n");
      out.write("            // Xử lý kết quả nếu cần\r\n");
      out.write("            console.log('Update successful');\r\n");
      out.write("            // Sau khi cập nhật, bạn có thể làm gì đó như hiển thị thông báo hoặc làm mới trang\r\n");
      out.write("            location.reload(); // Làm mới trang sau khi cập nhật\r\n");
      out.write("        },\r\n");
      out.write("        error: function(error) {\r\n");
      out.write("            console.error('Error updating quantity', error);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
