/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-12-11 10:55:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("@import url(\"https://fonts.googleapis.com/css?family=Fira+Sans\");\r\n");
      out.write("\r\n");
      out.write("html,body {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	background-color: #E1E8EE;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	font-family: \"Fira Sans\", Helvetica, Arial, sans-serif;\r\n");
      out.write("  -webkit-font-smoothing: antialiased;\r\n");
      out.write("  -moz-osx-font-smoothing: grayscale;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-structor {\r\n");
      out.write("	background-color: #222;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	height: 550px;\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	\r\n");
      out.write("	&::after {\r\n");
      out.write("		content: '';\r\n");
      out.write("		opacity: .8;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 0;right:0;bottom:0;left:0;\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("		background-position: left bottom;\r\n");
      out.write("		background-size: 500px;\r\n");
      out.write("		background-image: url('https://images.unsplash.com/photo-1503602642458-232111445657?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=bf884ad570b50659c5fa2dc2cfb20ecf&auto=format&fit=crop&w=1000&q=100');\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.signup {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 50%;\r\n");
      out.write("		left: 50%;\r\n");
      out.write("		-webkit-transform: translate(-50%, -50%);\r\n");
      out.write("		width: 65%;\r\n");
      out.write("		z-index: 5;\r\n");
      out.write("		-webkit-transition: all .3s ease;\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up {\r\n");
      out.write("			top: 5%;\r\n");
      out.write("			-webkit-transform: translate(-50%, 0%);\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up .form-holder,\r\n");
      out.write("		&.slide-up .submit-btn {\r\n");
      out.write("			opacity: 0;\r\n");
      out.write("			visibility: hidden;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up .form-title {\r\n");
      out.write("			font-size: 1em;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up .form-title span {\r\n");
      out.write("			margin-right: 5px;\r\n");
      out.write("			opacity: 1;\r\n");
      out.write("			visibility: visible;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.form-title {\r\n");
      out.write("			color: #fff;\r\n");
      out.write("			font-size: 1.7em;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			\r\n");
      out.write("			span {\r\n");
      out.write("				color: rgba(0,0,0,0.4);\r\n");
      out.write("				opacity: 0;\r\n");
      out.write("				visibility: hidden;\r\n");
      out.write("				-webkit-transition: all .3s ease;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.form-holder {\r\n");
      out.write("			border-radius: 15px;\r\n");
      out.write("			background-color: #fff;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("			margin-top: 50px;\r\n");
      out.write("			opacity: 1;\r\n");
      out.write("			visibility: visible;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("			\r\n");
      out.write("			.input {\r\n");
      out.write("				border: 0;\r\n");
      out.write("				outline: none;\r\n");
      out.write("				box-shadow: none;\r\n");
      out.write("				display: block;\r\n");
      out.write("				height: 30px;\r\n");
      out.write("				line-height: 30px;\r\n");
      out.write("				padding: 8px 15px;\r\n");
      out.write("				border-bottom: 1px solid #eee;\r\n");
      out.write("				width: 100%;\r\n");
      out.write("				font-size: 12px;\r\n");
      out.write("				\r\n");
      out.write("				&:last-child {\r\n");
      out.write("					border-bottom: 0;\r\n");
      out.write("				}\r\n");
      out.write("				&::-webkit-input-placeholder {\r\n");
      out.write("					color: rgba(0,0,0,0.4);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.submit-btn {\r\n");
      out.write("			background-color: rgba(0,0,0,0.4);\r\n");
      out.write("			color: rgba(256,256,256,0.7);\r\n");
      out.write("			border:0;\r\n");
      out.write("			border-radius: 15px;\r\n");
      out.write("			display: block;\r\n");
      out.write("			margin: 15px auto; \r\n");
      out.write("			padding: 15px 45px;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			font-size: 13px;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("			opacity: 1;\r\n");
      out.write("			visibility: visible;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("			\r\n");
      out.write("			&:hover {\r\n");
      out.write("				transition: all .3s ease;\r\n");
      out.write("				background-color: rgba(0,0,0,0.8);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.login {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 20%;\r\n");
      out.write("		left: 0;\r\n");
      out.write("		right: 0;\r\n");
      out.write("		bottom: 0;\r\n");
      out.write("		background-color: #fff;\r\n");
      out.write("		z-index: 5;\r\n");
      out.write("		-webkit-transition: all .3s ease;\r\n");
      out.write("		\r\n");
      out.write("		&::before {\r\n");
      out.write("			content: '';\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			left: 50%;\r\n");
      out.write("			top: -20px;\r\n");
      out.write("			-webkit-transform: translate(-50%, 0);\r\n");
      out.write("			background-color: #fff;\r\n");
      out.write("			width: 200%;\r\n");
      out.write("			height: 250px;\r\n");
      out.write("			border-radius: 50%;\r\n");
      out.write("			z-index: 4;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.center {\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			top: calc(50% - 10%);\r\n");
      out.write("			left: 50%;\r\n");
      out.write("			-webkit-transform: translate(-50%, -50%);\r\n");
      out.write("			width: 65%;\r\n");
      out.write("			z-index: 5;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("			\r\n");
      out.write("			.form-title {\r\n");
      out.write("				color: #000;\r\n");
      out.write("				font-size: 1.7em;\r\n");
      out.write("				text-align: center;\r\n");
      out.write("\r\n");
      out.write("				span {\r\n");
      out.write("					color: rgba(0,0,0,0.4);\r\n");
      out.write("					opacity: 0;\r\n");
      out.write("			    visibility: hidden;\r\n");
      out.write("				  -webkit-transition: all .3s ease;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.form-holder {\r\n");
      out.write("				border-radius: 15px;\r\n");
      out.write("				background-color: #fff;\r\n");
      out.write("				border: 1px solid #eee;\r\n");
      out.write("				overflow: hidden;\r\n");
      out.write("				margin-top: 50px;\r\n");
      out.write("				opacity: 1;\r\n");
      out.write("				visibility: visible;\r\n");
      out.write("				-webkit-transition: all .3s ease;\r\n");
      out.write("\r\n");
      out.write("				.input {\r\n");
      out.write("					border: 0;\r\n");
      out.write("					outline: none;\r\n");
      out.write("					box-shadow: none;\r\n");
      out.write("					display: block;\r\n");
      out.write("					height: 30px;\r\n");
      out.write("					line-height: 30px;\r\n");
      out.write("					padding: 8px 15px;\r\n");
      out.write("					border-bottom: 1px solid #eee;\r\n");
      out.write("					width: 100%;\r\n");
      out.write("					font-size: 12px;\r\n");
      out.write("\r\n");
      out.write("					&:last-child {\r\n");
      out.write("						border-bottom: 0;\r\n");
      out.write("					}\r\n");
      out.write("					&::-webkit-input-placeholder {\r\n");
      out.write("						color: rgba(0,0,0,0.4);\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.submit-btn {\r\n");
      out.write("				background-color: #6B92A4;\r\n");
      out.write("				color: rgba(256,256,256,0.7);\r\n");
      out.write("				border:0;\r\n");
      out.write("				border-radius: 15px;\r\n");
      out.write("				display: block;\r\n");
      out.write("				margin: 15px auto; \r\n");
      out.write("				padding: 15px 45px;\r\n");
      out.write("				width: 100%;\r\n");
      out.write("				font-size: 13px;\r\n");
      out.write("				font-weight: bold;\r\n");
      out.write("				cursor: pointer;\r\n");
      out.write("				opacity: 1;\r\n");
      out.write("				visibility: visible;\r\n");
      out.write("				-webkit-transition: all .3s ease;\r\n");
      out.write("\r\n");
      out.write("				&:hover {\r\n");
      out.write("					transition: all .3s ease;\r\n");
      out.write("					background-color: rgba(0,0,0,0.8);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up {\r\n");
      out.write("			top: 90%;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up .center {\r\n");
      out.write("			top: 10%;\r\n");
      out.write("			-webkit-transform: translate(-50%, 0%);\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up .form-holder,\r\n");
      out.write("		&.slide-up .submit-btn {\r\n");
      out.write("			opacity: 0;\r\n");
      out.write("			visibility: hidden;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up .form-title {\r\n");
      out.write("			font-size: 1em;\r\n");
      out.write("			margin: 0;\r\n");
      out.write("			padding: 0;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		&.slide-up .form-title span {\r\n");
      out.write("			margin-right: 5px;\r\n");
      out.write("			opacity: 1;\r\n");
      out.write("			visibility: visible;\r\n");
      out.write("			-webkit-transition: all .3s ease;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-structor\">\r\n");
      out.write("<form action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("	<div class=\"signup\">\r\n");
      out.write("		<h2 class=\"form-title\" id=\"signup\">Sign up</h2>\r\n");
      out.write("		<div class=\"form-holder\">\r\n");
      out.write("			<input type=\"text\" class=\"input\" placeholder=\"Name\" />\r\n");
      out.write("			<input type=\"email\" class=\"input\" placeholder=\"Username\" />\r\n");
      out.write("			<input type=\"password\" class=\"input\" placeholder=\"Password\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		<button class=\"submit-btn\">Sign up</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"login slide-up\">\r\n");
      out.write("		<div class=\"center\">\r\n");
      out.write("			<h2 class=\"form-title\" id=\"login\">Log in</h2>\r\n");
      out.write("			<div class=\"form-holder\">\r\n");
      out.write("				<input type=\"text\" class=\"input\" placeholder=\"Username\" name=\"username\" />\r\n");
      out.write("				<input type=\"password\" class=\"input\" placeholder=\"Password\"  name=\"password\"/>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input class=\"submit-btn\" type=\"submit\" value=\"Login\">\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("console.clear();\r\n");
      out.write("\r\n");
      out.write("const loginBtn = document.getElementById('login');\r\n");
      out.write("const signupBtn = document.getElementById('signup');\r\n");
      out.write("\r\n");
      out.write("loginBtn.addEventListener('click', (e) => {\r\n");
      out.write("	let parent = e.target.parentNode.parentNode;\r\n");
      out.write("	Array.from(e.target.parentNode.parentNode.classList).find((element) => {\r\n");
      out.write("		if(element !== \"slide-up\") {\r\n");
      out.write("			parent.classList.add('slide-up')\r\n");
      out.write("		}else{\r\n");
      out.write("			signupBtn.parentNode.classList.add('slide-up')\r\n");
      out.write("			parent.classList.remove('slide-up')\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("signupBtn.addEventListener('click', (e) => {\r\n");
      out.write("	let parent = e.target.parentNode;\r\n");
      out.write("	Array.from(e.target.parentNode.classList).find((element) => {\r\n");
      out.write("		if(element !== \"slide-up\") {\r\n");
      out.write("			parent.classList.add('slide-up')\r\n");
      out.write("		}else{\r\n");
      out.write("			loginBtn.parentNode.parentNode.classList.add('slide-up')\r\n");
      out.write("			parent.classList.remove('slide-up')\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
