/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-12-06 04:36:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import dao.WatchDAO;
import com.mysql.cj.x.protobuf.MysqlxDatatypes.Array;
import core.Category;
import core.Watch;
import java.util.ArrayList;
import core.Category;
import java.util.ArrayList;

public final class productdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1697639205471L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1700108822581L));
    _jspx_dependants.put("jar:file:/C:/Users/szers/OneDrive/Máy%20tính/MyProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/MyProject/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1701060110985L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("core.Category");
    _jspx_imports_classes.add("core.Watch");
    _jspx_imports_classes.add("dao.WatchDAO");
    _jspx_imports_classes.add("com.mysql.cj.x.protobuf.MysqlxDatatypes.Array");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>My Store</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css\" />\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Jost:wght@300;400;500&family=Lato:wght@300;400;700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- script\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("<script src=\"js/modernizr.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-bs-spy=\"scroll\" data-bs-target=\"#navbar\"\r\n");
      out.write("	data-bs-root-margin=\"0px 0px -40%\" data-bs-smooth-scroll=\"true\"\r\n");
      out.write("	tabindex=\"0\">\r\n");
      out.write("\r\n");
      out.write("	<svg xmlns=\"http://www.w3.org/2000/svg\" style=\"display: none;\">\r\n");
      out.write("      <symbol id=\"search\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("			viewBox=\"0 0 32 32\">\r\n");
      out.write("        <title>Search</title>\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M19 3C13.488 3 9 7.488 9 13c0 2.395.84 4.59 2.25 6.313L3.281 27.28l1.439 1.44l7.968-7.969A9.922 9.922 0 0 0 19 23c5.512 0 10-4.488 10-10S24.512 3 19 3zm0 2c4.43 0 8 3.57 8 8s-3.57 8-8 8s-8-3.57-8-8s3.57-8 8-8z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"user\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"cart\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <svg xmlns=\"http://www.w3.org/2000/svg\" id=\"chevron-left\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path fill-rule=\"evenodd\"\r\n");
      out.write("				d=\"M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z\" />\r\n");
      out.write("      </svg>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"chevron-right\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path fill-rule=\"evenodd\"\r\n");
      out.write("			d=\"M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"cart-outline\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"quality\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z\" />\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"price-tag\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M6 4.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-1 0a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0z\" />\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M2 1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 1 6.586V2a1 1 0 0 1 1-1zm0 5.586 7 7L13.586 9l-7-7H2v4.586z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"shield-plus\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.893.533.12.057.218.095.293.118a.55.55 0 0 0 .101.025.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z\" />\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M8 4.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V9a.5.5 0 0 1-1 0V7.5H6a.5.5 0 0 1 0-1h1.5V5a.5.5 0 0 1 .5-.5z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"star-fill\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"star-empty\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"star-half\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M5.354 5.119 7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.548.548 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.52.52 0 0 1-.146.05c-.342.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.172-.403.58.58 0 0 1 .085-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027a.5.5 0 0 1 .232.056l3.686 1.894-.694-3.957a.565.565 0 0 1 .162-.505l2.907-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.001 2.223 8 2.226v9.8z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"quote\"\r\n");
      out.write("			viewBox=\"0 0 24 24\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"m15 17l2-4h-4V6h7v7l-2 4h-3Zm-9 0l2-4H4V6h7v7l-2 4H6Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"facebook\"\r\n");
      out.write("			viewBox=\"0 0 24 24\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M9.198 21.5h4v-8.01h3.604l.396-3.98h-4V7.5a1 1 0 0 1 1-1h3v-4h-3a5 5 0 0 0-5 5v2.01h-2l-.396 3.98h2.396v8.01Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"youtube\"\r\n");
      out.write("			viewBox=\"0 0 32 32\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M29.41 9.26a3.5 3.5 0 0 0-2.47-2.47C24.76 6.2 16 6.2 16 6.2s-8.76 0-10.94.59a3.5 3.5 0 0 0-2.47 2.47A36.13 36.13 0 0 0 2 16a36.13 36.13 0 0 0 .59 6.74a3.5 3.5 0 0 0 2.47 2.47c2.18.59 10.94.59 10.94.59s8.76 0 10.94-.59a3.5 3.5 0 0 0 2.47-2.47A36.13 36.13 0 0 0 30 16a36.13 36.13 0 0 0-.59-6.74ZM13.2 20.2v-8.4l7.27 4.2Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"twitter\"\r\n");
      out.write("			viewBox=\"0 0 256 256\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"m245.66 77.66l-29.9 29.9C209.72 177.58 150.67 232 80 232c-14.52 0-26.49-2.3-35.58-6.84c-7.33-3.67-10.33-7.6-11.08-8.72a8 8 0 0 1 3.85-11.93c.26-.1 24.24-9.31 39.47-26.84a110.93 110.93 0 0 1-21.88-24.2c-12.4-18.41-26.28-50.39-22-98.18a8 8 0 0 1 13.65-4.92c.35.35 33.28 33.1 73.54 43.72V88a47.87 47.87 0 0 1 14.36-34.3A46.87 46.87 0 0 1 168.1 40a48.66 48.66 0 0 1 41.47 24H240a8 8 0 0 1 5.66 13.66Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"instagram\"\r\n");
      out.write("			viewBox=\"0 0 256 256\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M128 80a48 48 0 1 0 48 48a48.05 48.05 0 0 0-48-48Zm0 80a32 32 0 1 1 32-32a32 32 0 0 1-32 32Zm48-136H80a56.06 56.06 0 0 0-56 56v96a56.06 56.06 0 0 0 56 56h96a56.06 56.06 0 0 0 56-56V80a56.06 56.06 0 0 0-56-56Zm40 152a40 40 0 0 1-40 40H80a40 40 0 0 1-40-40V80a40 40 0 0 1 40-40h96a40 40 0 0 1 40 40ZM192 76a12 12 0 1 1-12-12a12 12 0 0 1 12 12Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"linkedin\"\r\n");
      out.write("			viewBox=\"0 0 24 24\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M6.94 5a2 2 0 1 1-4-.002a2 2 0 0 1 4 .002zM7 8.48H3V21h4V8.48zm6.32 0H9.34V21h3.94v-6.57c0-3.66 4.77-4 4.77 0V21H22v-7.93c0-6.17-7.06-5.94-8.72-2.91l.04-1.68z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"nav-icon\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M14 10.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0 0 1h7a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"close\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"navbar-icon\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M14 10.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0 0 1h7a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("    </svg>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"search-popup\">\r\n");
      out.write("		<div class=\"search-popup-container\">\r\n");
      out.write("\r\n");
      out.write("			<form role=\"search\" method=\"get\" class=\"search-form\"\r\n");
      out.write("				action=\"SearchServlet\">\r\n");
      out.write("				<input type=\"search\" id=\"search-form\" class=\"search-field\"\r\n");
      out.write("					placeholder=\"Type and press enter\" value=\"\" name=\"search\" />\r\n");
      out.write("				<button type=\"submit\" class=\"search-submit\">\r\n");
      out.write("					<svg class=\"search\">\r\n");
      out.write("						<use xlink:href=\"#search\"></use></svg>\r\n");
      out.write("				</button>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("			<h5 class=\"cat-list-title\">Browse Categories</h5>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"cat-list\">\r\n");
      out.write("				<li class=\"cat-list-item\"><a href=\"#\" title=\"Mobile Phones\">Mobile\r\n");
      out.write("						Phones</a></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<svg xmlns=\"http://www.w3.org/2000/svg\" style=\"display: none;\">\r\n");
      out.write("      <symbol id=\"search\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("			viewBox=\"0 0 32 32\">\r\n");
      out.write("        <title>Search</title>\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M19 3C13.488 3 9 7.488 9 13c0 2.395.84 4.59 2.25 6.313L3.281 27.28l1.439 1.44l7.968-7.969A9.922 9.922 0 0 0 19 23c5.512 0 10-4.488 10-10S24.512 3 19 3zm0 2c4.43 0 8 3.57 8 8s-3.57 8-8 8s-8-3.57-8-8s3.57-8 8-8z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("    <a href=\"login.jsp\">  <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"user\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z\" />\r\n");
      out.write("      </symbol></a>\r\n");
      out.write("      <a><symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"cart\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z\" />\r\n");
      out.write("      </symbol>0</a>\r\n");
      out.write("      <svg xmlns=\"http://www.w3.org/2000/svg\" id=\"chevron-left\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path fill-rule=\"evenodd\"\r\n");
      out.write("				d=\"M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z\" />\r\n");
      out.write("      </svg>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"chevron-right\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path fill-rule=\"evenodd\"\r\n");
      out.write("			d=\"M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"cart-outline\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"quality\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z\" />\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"price-tag\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M6 4.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-1 0a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0z\" />\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M2 1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 1 6.586V2a1 1 0 0 1 1-1zm0 5.586 7 7L13.586 9l-7-7H2v4.586z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"shield-plus\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.893.533.12.057.218.095.293.118a.55.55 0 0 0 .101.025.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z\" />\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M8 4.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V9a.5.5 0 0 1-1 0V7.5H6a.5.5 0 0 1 0-1h1.5V5a.5.5 0 0 1 .5-.5z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"star-fill\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"star-empty\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"star-half\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M5.354 5.119 7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.548.548 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.52.52 0 0 1-.146.05c-.342.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.172-.403.58.58 0 0 1 .085-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027a.5.5 0 0 1 .232.056l3.686 1.894-.694-3.957a.565.565 0 0 1 .162-.505l2.907-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.001 2.223 8 2.226v9.8z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"quote\"\r\n");
      out.write("			viewBox=\"0 0 24 24\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"m15 17l2-4h-4V6h7v7l-2 4h-3Zm-9 0l2-4H4V6h7v7l-2 4H6Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"facebook\"\r\n");
      out.write("			viewBox=\"0 0 24 24\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M9.198 21.5h4v-8.01h3.604l.396-3.98h-4V7.5a1 1 0 0 1 1-1h3v-4h-3a5 5 0 0 0-5 5v2.01h-2l-.396 3.98h2.396v8.01Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"youtube\"\r\n");
      out.write("			viewBox=\"0 0 32 32\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M29.41 9.26a3.5 3.5 0 0 0-2.47-2.47C24.76 6.2 16 6.2 16 6.2s-8.76 0-10.94.59a3.5 3.5 0 0 0-2.47 2.47A36.13 36.13 0 0 0 2 16a36.13 36.13 0 0 0 .59 6.74a3.5 3.5 0 0 0 2.47 2.47c2.18.59 10.94.59 10.94.59s8.76 0 10.94-.59a3.5 3.5 0 0 0 2.47-2.47A36.13 36.13 0 0 0 30 16a36.13 36.13 0 0 0-.59-6.74ZM13.2 20.2v-8.4l7.27 4.2Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"twitter\"\r\n");
      out.write("			viewBox=\"0 0 256 256\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"m245.66 77.66l-29.9 29.9C209.72 177.58 150.67 232 80 232c-14.52 0-26.49-2.3-35.58-6.84c-7.33-3.67-10.33-7.6-11.08-8.72a8 8 0 0 1 3.85-11.93c.26-.1 24.24-9.31 39.47-26.84a110.93 110.93 0 0 1-21.88-24.2c-12.4-18.41-26.28-50.39-22-98.18a8 8 0 0 1 13.65-4.92c.35.35 33.28 33.1 73.54 43.72V88a47.87 47.87 0 0 1 14.36-34.3A46.87 46.87 0 0 1 168.1 40a48.66 48.66 0 0 1 41.47 24H240a8 8 0 0 1 5.66 13.66Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"instagram\"\r\n");
      out.write("			viewBox=\"0 0 256 256\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M128 80a48 48 0 1 0 48 48a48.05 48.05 0 0 0-48-48Zm0 80a32 32 0 1 1 32-32a32 32 0 0 1-32 32Zm48-136H80a56.06 56.06 0 0 0-56 56v96a56.06 56.06 0 0 0 56 56h96a56.06 56.06 0 0 0 56-56V80a56.06 56.06 0 0 0-56-56Zm40 152a40 40 0 0 1-40 40H80a40 40 0 0 1-40-40V80a40 40 0 0 1 40-40h96a40 40 0 0 1 40 40ZM192 76a12 12 0 1 1-12-12a12 12 0 0 1 12 12Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"linkedin\"\r\n");
      out.write("			viewBox=\"0 0 24 24\">\r\n");
      out.write("        <path fill=\"currentColor\"\r\n");
      out.write("			d=\"M6.94 5a2 2 0 1 1-4-.002a2 2 0 0 1 4 .002zM7 8.48H3V21h4V8.48zm6.32 0H9.34V21h3.94v-6.57c0-3.66 4.77-4 4.77 0V21H22v-7.93c0-6.17-7.06-5.94-8.72-2.91l.04-1.68z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"nav-icon\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M14 10.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0 0 1h7a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"close\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"navbar-icon\"\r\n");
      out.write("			viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path\r\n");
      out.write("			d=\"M14 10.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0 0 1h7a.5.5 0 0 0 .5-.5zm0-3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5z\" />\r\n");
      out.write("      </symbol>\r\n");
      out.write("    </svg>\r\n");
      out.write("	<header id=\"header\"\r\n");
      out.write("		class=\"site-header header-scrolled position-fixed text-black bg-light\">\r\n");
      out.write("		<nav id=\"header-nav\" class=\"navbar navbar-expand-lg px-3 mb-3\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.html\"> <img\r\n");
      out.write("					src=\"images/main-logo.png\" class=\"logo\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<button class=\"navbar-toggler d-flex d-lg-none order-3 p-2\"\r\n");
      out.write("					type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#bdNavbar\"\r\n");
      out.write("					aria-controls=\"bdNavbar\" aria-expanded=\"false\"\r\n");
      out.write("					aria-label=\"Toggle navigation\">\r\n");
      out.write("					<svg class=\"navbar-icon\">\r\n");
      out.write("              <use xlink:href=\"#navbar-icon\"></use>\r\n");
      out.write("            </svg>\r\n");
      out.write("				</button>\r\n");
      out.write("				<div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"bdNavbar\"\r\n");
      out.write("					aria-labelledby=\"bdNavbarOffcanvasLabel\">\r\n");
      out.write("					<div class=\"offcanvas-header px-4 pb-0\">\r\n");
      out.write("						<a class=\"navbar-brand\" href=\"index.html\"> <img\r\n");
      out.write("							src=\"images/main-logo.png\" class=\"logo\">\r\n");
      out.write("						</a>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close btn-close-black\"\r\n");
      out.write("							data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"\r\n");
      out.write("							data-bs-target=\"#bdNavbar\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offcanvas-body\">\r\n");
      out.write("						<ul id=\"navbar\"\r\n");
      out.write("							class=\"navbar-nav text-uppercase justify-content-end align-items-center flex-grow-1 pe-3\">\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link me-4 active\"\r\n");
      out.write("								href=\"ShowAllProductServlet\">Home</a></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link me-4\"\r\n");
      out.write("								href=\"#latest-blog\">Products</a></li>\r\n");
      out.write("							<ul class=\"dropdown-menu\">\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"nav-item\">\r\n");
      out.write("							<li class=\"nav-item dropdown\"><a\r\n");
      out.write("								class=\"nav-link me-4 dropdown-toggle link-dark\"\r\n");
      out.write("								data-bs-toggle=\"dropdown\" href=\"#\" role=\"button\"\r\n");
      out.write("								aria-expanded=\"false\">Categories</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("\r\n");
      out.write("									");
 ArrayList<Category> listCategory = (ArrayList<Category>) request.getAttribute("listCategory");
									String name = (String) session.getAttribute("username");
									
      out.write("\r\n");
      out.write("									");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									<li><a href=\"shop.html\" class=\"dropdown-item\"></a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"nav-item\">\r\n");
      out.write("								<div class=\"user-items ps-5\">\r\n");
      out.write("									<ul class=\"d-flex justify-content-end list-unstyled\">\r\n");
      out.write("										<li class=\"search-item pe-3\"><a href=\"#\"\r\n");
      out.write("											class=\"search-button\"> <svg class=\"search\">\r\n");
      out.write("                            <use xlink:href=\"#search\"></use>\r\n");
      out.write("                          </svg>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										\r\n");
      out.write("										<li><a href=\"cart.jsp\"> <svg class=\"cart\">\r\n");
      out.write("                            <use xlink:href=\"#cart\"></use>\r\n");
      out.write("                          </svg>\r\n");
      out.write("                          </a></li>\r\n");
      out.write("                          ");
 //String username = (String) session.getAttribute("username");
							if(name != null)	{                          
                          
      out.write("\r\n");
      out.write("										<a class=\"btn btn-primary\" href=\"#\" style=\"padding: 5px;margin: 0 25px\" > hello ");
      out.print( name );
      out.write("  </a>\r\n");
      out.write("										<a class=\"btn btn-primary\" href=\"LogoutServlet\" >Logout</a>\r\n");
      out.write("									");
 }else{ 
      out.write("\r\n");
      out.write("								<li class=\"pe-3\" style=\"margin-left: 15px;\"><a href=\"login.jsp\"> <svg class=\"user\">\r\n");
      out.write("                            <use xlink:href=\"#user\"></use>\r\n");
      out.write("                          </svg>		\r\n");
      out.write("                          </a></li>\r\n");
      out.write("						");
 }
      out.write("\r\n");
      out.write("							\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
 Watch watch = (Watch) request.getAttribute("watch"); 
      out.write("\r\n");
      out.write("	<div class=\"container padding-large\">\r\n");
      out.write("		<div class=\"row gx-5\">\r\n");
      out.write("			<aside class=\"col-lg-6\">\r\n");
      out.write("				<div class=\"border rounded-4 mb-3 d-flex justify-content-center\">\r\n");
      out.write("					<a data-fslightbox=\"mygalley\" class=\"rounded-4\" target=\"_blank\"\r\n");
      out.write("						data-type=\"image\"\r\n");
      out.write("						href=\"./images/insta-item4.jpg\">\r\n");
      out.write("						<img style=\"max-width: 100%; max-height: 100vh; margin: auto;\"\r\n");
      out.write("						class=\"rounded-4 fit\"\r\n");
      out.write("						src=\"./images/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${watch.watchImage}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- thumbs-wrap.// -->\r\n");
      out.write("				<!-- gallery-wrap .end// -->\r\n");
      out.write("			</aside>\r\n");
      out.write("			\r\n");
      out.write("			<main class=\"col-lg-6\">\r\n");
      out.write("				<div class=\"ps-lg-3\">\r\n");
      out.write("					<h4 class=\"title text-dark\">\r\n");
      out.write("						");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${watch.watchName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					</h4>\r\n");
      out.write("					<div class=\"d-flex flex-row my-3\">\r\n");
      out.write("						<div class=\"text-warning mb-1 me-2\">\r\n");
      out.write("							<i class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i\r\n");
      out.write("								class=\"fa fa-star\"></i> <i class=\"fa fa-star\"></i> <i\r\n");
      out.write("								class=\"fas fa-star-half-alt\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<span class=\"h5\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${watch.watchPrice }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${watch.watchDescription}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("					<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${watch.quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("					\r\n");
      out.write("					<hr />\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row mb-4\">\r\n");
      out.write("						<div class=\"col-md-4 col-6\">\r\n");
      out.write("							<label class=\"mb-2\">Size</label> <select\r\n");
      out.write("								class=\"form-select border border-secondary\"\r\n");
      out.write("								style=\"height: 35px;\">\r\n");
      out.write("								<option>Small</option>\r\n");
      out.write("								<option>Medium</option>\r\n");
      out.write("								<option>Large</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- col.// -->\r\n");
      out.write("						<div class=\"col-md-4 col-6 mb-3\">\r\n");
      out.write("							<label class=\"mb-2 d-block\">Quantity</label>\r\n");
      out.write("							<div class=\"input-group mb-3\" style=\"width: 170px;\">\r\n");
      out.write("\r\n");
      out.write("								<input type=\"number\"\r\n");
      out.write("									class=\"form-control text-center border border-secondary\"\r\n");
      out.write("									placeholder=\"0\" aria-label=\"Example text with button addon\"\r\n");
      out.write("									aria-describedby=\"button-addon1\" />\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<a href=\"#\" class=\"btn btn-warning shadow-0\"> Buy now </a> <a\r\n");
      out.write("						href=\"#\" class=\"btn btn-primary shadow-0\"> <i\r\n");
      out.write("						class=\"me-1 fa fa-shopping-basket\"></i> Add to cart\r\n");
      out.write("					</a> <a href=\"#\"\r\n");
      out.write("						class=\"btn btn-light border border-secondary py-2 icon-hover px-3\">\r\n");
      out.write("						<i class=\"me-1 fa fa-heart fa-lg\"></i> Save\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</main>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<footer id=\"footer\" class=\"overflow-hidden\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"footer-top-area\">\r\n");
      out.write("					<div class=\"row d-flex flex-wrap justify-content-between\">\r\n");
      out.write("						<div class=\"col-lg-3 col-sm-6 pb-3\">\r\n");
      out.write("							<div class=\"footer-menu\">\r\n");
      out.write("								<img src=\"images/main-logo.png\" alt=\"logo\">\r\n");
      out.write("								<p>Nisi, purus vitae, ultrices nunc. Sit ac sit suscipit\r\n");
      out.write("									hendrerit. Gravida massa volutpat aenean odio erat nullam\r\n");
      out.write("									fringilla.</p>\r\n");
      out.write("								<div class=\"social-links\">\r\n");
      out.write("									<ul class=\"d-flex list-unstyled\">\r\n");
      out.write("										<li><a href=\"#\"> <svg class=\"facebook\">\r\n");
      out.write("                            <use xlink:href=\"#facebook\" />\r\n");
      out.write("                          </svg>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\"> <svg class=\"instagram\">\r\n");
      out.write("                            <use xlink:href=\"#instagram\" />\r\n");
      out.write("                          </svg>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\"> <svg class=\"twitter\">\r\n");
      out.write("                            <use xlink:href=\"#twitter\" />\r\n");
      out.write("                          </svg>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\"> <svg class=\"linkedin\">\r\n");
      out.write("                            <use xlink:href=\"#linkedin\" />\r\n");
      out.write("                          </svg>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\"> <svg class=\"youtube\">\r\n");
      out.write("                            <use xlink:href=\"#youtube\" />\r\n");
      out.write("                          </svg>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-2 col-sm-6 pb-3\">\r\n");
      out.write("							<div class=\"footer-menu text-uppercase\">\r\n");
      out.write("								<h5 class=\"widget-title pb-2\">Quick Links</h5>\r\n");
      out.write("								<ul class=\"menu-list list-unstyled text-uppercase\">\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Home</a></li>\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">About</a></li>\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Shop</a></li>\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Blogs</a></li>\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Contact</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-sm-6 pb-3\">\r\n");
      out.write("							<div class=\"footer-menu text-uppercase\">\r\n");
      out.write("								<h5 class=\"widget-title pb-2\">Help & Info Help</h5>\r\n");
      out.write("								<ul class=\"menu-list list-unstyled\">\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Track Your\r\n");
      out.write("											Order</a></li>\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Returns\r\n");
      out.write("											Policies</a></li>\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Shipping +\r\n");
      out.write("											Delivery</a></li>\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("									<li class=\"menu-item pb-2\"><a href=\"#\">Faqs</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-sm-6 pb-3\">\r\n");
      out.write("							<div class=\"footer-menu contact-item\">\r\n");
      out.write("								<h5 class=\"widget-title text-uppercase pb-2\">Contact Us</h5>\r\n");
      out.write("								<p>\r\n");
      out.write("									Do you have any queries or suggestions? <a href=\"mailto:\">yourinfo@gmail.com</a>\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									If you need support? Just give us a call. <a href=\"\">+55\r\n");
      out.write("										111 222 333 44</a>\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<div id=\"footer-bottom\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row d-flex flex-wrap justify-content-between\">\r\n");
      out.write("				<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"Shipping d-flex\">\r\n");
      out.write("						<p>We ship with:</p>\r\n");
      out.write("						<div class=\"card-wrap ps-2\">\r\n");
      out.write("							<img src=\"images/dhl.png\" alt=\"visa\"> <img\r\n");
      out.write("								src=\"images/shippingcard.png\" alt=\"mastercard\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"payment-method d-flex\">\r\n");
      out.write("						<p>Payment options:</p>\r\n");
      out.write("						<div class=\"card-wrap ps-2\">\r\n");
      out.write("							<img src=\"images/visa.jpg\" alt=\"visa\"> <img\r\n");
      out.write("								src=\"images/mastercard.jpg\" alt=\"mastercard\"> <img\r\n");
      out.write("								src=\"images/paypal.jpg\" alt=\"paypal\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"copyright\">\r\n");
      out.write("						<p>\r\n");
      out.write("							© Copyright 2023 MiniStore. Design by <a\r\n");
      out.write("								href=\"https://templatesjungle.com/\">TemplatesJungle</a>\r\n");
      out.write("							Distribution by <a href=\"https://themewagon.com\">ThemeWagon</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<script src=\"js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/plugins.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /header.jsp(172,9) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/header.jsp(172,9) '${listCategory }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listCategory }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /header.jsp(172,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("										<li><a href=\"ShowAllProductServlet?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.idCatogery}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("											class=\"dropdown-item\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.nameCategory}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
